backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ExtendedEnvActionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ExtendedEnvActionSurveillanceEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/GetEnvActionByIdAndMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/bff/model/action/Action.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/bff/model/action/EnvActionData.kt, frontend/src/pam/mission/actions/action-mapping.ts, frontend/src/pam/mission/actions/action-rescue-form.tsx, frontend/src/pam/mission/actions/action-selection-dropdown.tsx, frontend/src/pam/mission/actions/action-surveillance-env.test.tsx, frontend/src/pam/mission/actions/action-surveillance-env.tsx, frontend/src/pam/mission/mission-content.tsx, frontend/src/pam/mission/timeline/item/timeline-item-container.tsx, frontend/src/pam/mission/timeline/item/timeline-item-rescue.tsx, frontend/src/pam/mission/timeline/item/timeline-item-surveillance.test.tsx, frontend/src/pam/mission/timeline/item/timeline-item-surveillance.tsx, frontend/src/pam/mission/timeline/item/timeline-item.tsx, frontend/src/types/action-types.ts
Add `Événements` functionality to actions and timeline
This pull request introduces the `Événements` functionality to both actions and the timeline. 
- Integrated `Événements` into the timeline
- Added `Événements` functionality to actions
- Tested the functionality thoroughly to ensure proper integration
- Conducted unit tests to verify the accuracy of `Événements` handling
- Reviewed and tested edge cases to ensure robustness
=> [feature] Evenements

Makefile, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ActionRescueEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/FormatActionsForTimeline.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/FormatActionsForTimelineTests.kt, frontend/src/pam/mission/actions/action-illegal-immigration-form.tsx, frontend/src/pam/mission/actions/action-rescue-form.tsx, frontend/src/pam/mission/actions/action-selection-dropdown.test.tsx, frontend/src/pam/mission/actions/action-selection-dropdown.tsx, frontend/src/pam/mission/controls/env-control-form.tsx, frontend/src/pam/mission/controls/utils.ts, frontend/src/pam/mission/infractions/env-infraction-target-added-by-unit-form.tsx, frontend/src/pam/mission/infractions/natinfs-multi-select.tsx, frontend/src/pam/mission/timeline/item/timeline-item-illegal-immigration.tsx, frontend/src/pam/mission/timeline/item/timeline-item-rescue.test.tsx, frontend/src/pam/mission/timeline/item/timeline-item-rescue.tsx
Liste des fix:
https://docs.google.com/presentation/d/1KpkFeNQ4odo6RzUdeX2uPvO-3o_Cm3KdgZIpgPG3kdw/edit#slide=id.g2e2f9108ff3_0_135
=> Fixes after test session

.github/workflows/codeql.yml, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/user/RoleTypeEnum.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/user/UserEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/auth/TokenService.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/auth/ApiAuthController.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/auth/adapters/inputs/AuthRegisterDataInput.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/user/UserModel.kt, backend/src/main/resources/db/migration/V1.2024.05.28.10.40__alter_user_add_roles.sql, backend/src/main/resources/graphql/user.graphqls, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/auth/TokenServiceTests.kt
- Add roles to user database
- encode these roles in jwt token
=> feat(backend): user roles in token

frontend/src/pam/mission/actions/action-surveillance-env.test.tsx, frontend/src/pam/mission/actions/action-surveillance-env.tsx, frontend/src/pam/mission/mission-page.test.tsx, frontend/src/pam/mission/mission-page.tsx
=> fix(SurveillanceEnv): fix themes/subthemes

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/UpdateMissionService.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/UpdateMissionServiceTest.kt
- Optional getOrnull
- Create Entity if null and save
- Test
=> fix(ServiceId): update service id event if generalInformation is null

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/MissionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/MissionStatusEnum.kt, backend/src/main/resources/graphql/mission.graphqls, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/MissionEntityTests.kt, frontend/src/pam/mission/mission-status-tag.test.tsx, frontend/src/pam/mission/mission-status-tag.tsx, frontend/src/types/mission-types.ts
J'en ai profité pour enlever la ocnfusion entre les statuts UPCOMING et PENDING qui étaient la même chose au final
=> fix: Mission status is wrong when no endDateTime #227

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/FormatActionsForTimeline.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/FormatActionsForTimelineTests.kt
description dans l'issue github
=> fix(RapportDePatrouille): escape special chars #234

.gitlab-ci.yml, backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/monitorenv/APIEnvMissionRepository.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/monitorenv/APIEnvMissionRepositoryTest.kt, frontend/package-lock.json, frontend/package.json, frontend/src/pam/mission/mission-observation-unit.test.tsx, frontend/src/pam/mission/mission-observations-unit.tsx, frontend/src/pam/mission/panel-general-info.tsx, frontend/src/pam/mission/use-patch-mission-env.tsx
and harmonize "observation" -> "observations"
=> fix(patchMission): add more logging

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ActionAntiPollutionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/utils/FillAEMExcelRow.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/adapters/action/ActionAntiPollutionInput.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/action/NavActionAntiPollution.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/action/ActionAntiPollutionModel.kt, backend/src/main/resources/db/migration/V1.2024.07.24.15.40__add_anti_pollution_action_simple_brewing_column_and_anti_pol_device_column.sql, backend/src/main/resources/graphql/action.graphqls, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/mission/nav/action/ActionAntiPollutionEntityTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/bff/adapters/action/ActionAntiPollutionInputTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/action/ActionAntiPollutionModelTest.kt, frontend/src/pam/mission/actions/action-anti-pollution-form.test.tsx, frontend/src/pam/mission/actions/action-anti-pollution-form.tsx, frontend/src/pam/mission/actions/use-action-by-id.tsx, frontend/src/pam/mission/others/anti-pollution/use-add-anti-pollution.tsx, frontend/src/types/action-types.ts
=> Feature - 266 aem front back add new attributes part 2

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/ExportMissionAEM.kt
- use from Mission instead of from action to get nbrOfVeselRecognized
=> fix(AEM): export from mission

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/config/SecurityConfig.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/admin/ApiAdminController.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/api/admin/ApiAdminControllerITest.kt
- Configure the security config to denied admin url except if user has authority
- in user claims add authority from roles
- Add admin controller + authority
- Test apiAdminController
=> feat(admin): admin controller + restriction roles

frontend/src/sentry.ts
Petit test sur des nouvelles features de Sentry, je sais pas trop si ca va etre utile ou pas.
=> feat(Sentry): add profiling sampling in frontend

frontend/src/features/pam/mission/components/elements/mission-observation-unit.test.tsx, frontend/src/features/pam/mission/components/elements/mission-observations-unit.tsx
- Had delay trigger of 5sec on the form.
- filter only init trigger (oldValue === newValue)
- Add tests
=> fix(observation-unit): empty case

backend/src/main/resources/db/migration/V1.2024.08.29.16.15__update_agent_service_themis.sql
- Add new member to Themis bordé B$
- Remove old value of second
=> fix(agent-service): update Themis bordée B  crew list

frontend/src/features/pam/mission/components/elements/general-info/mission-recognized-vessel.test.tsx, frontend/src/features/pam/mission/components/elements/general-info/mission-recognized-vessel.tsx, frontend/src/features/pam/mission/hooks/use-mission-by-id.tsx, frontend/src/features/pam/mission/hooks/use-mission-excerpt.tsx
- Update query to select field nbrRecognizedVessel
- Update trigger changes wit 5sec delay
- Add isRequired attribute to show mandatory
- update test
=> fix(general-information): nbr recognized vessel select query

frontend/src/features/common/components/ui/coordinates-input-dmd.test.tsx, frontend/src/features/common/components/ui/coordonates-input-dmd.tsx, frontend/src/features/pam/mission/components/elements/actions/action-anti-pollution-form.test.tsx, frontend/src/features/pam/mission/components/elements/actions/action-anti-pollution-form.tsx, frontend/src/features/pam/mission/components/elements/actions/action-control-nav.tsx, frontend/src/features/pam/mission/components/elements/actions/action-illegal-immigration-form.tsx, frontend/src/features/pam/mission/components/elements/actions/action-rescue-form.tsx
- Create coordnate-input-dmd with place holder
- test the new component
- replace where it might be useful
=> feat(coords): add place holder over coordonates

frontend/src/features/pam/mission/components/elements/actions/fish/fish-control-species-section.test.tsx, frontend/src/features/pam/mission/components/elements/actions/fish/fish-control-species-section.tsx
- Add read only attribute over all radio button
- add light tests
=> fix(fish-control): add readonly over radio button

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMSovereignProtect.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMTableExport.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ActionStatusEntity.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMSovereignProtectTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMTableExportTest.kt, frontend/package-lock.json, frontend/package.json
- Update algorithm of nbrHourAtSea
- Update tests around
=> fix(aem): sovereign nbr hour at sea

frontend/src/features/pam/mission/components/elements/actions/action-control-env.tsx, frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.test.tsx, frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.test.tsx, frontend/src/features/pam/mission/components/elements/controls/env-control-form.tsx, frontend/src/features/pam/mission/hooks/control/use-control.test.tsx, frontend/src/features/pam/mission/hooks/control/use-control.tsx
- Update EnvControlForm to  use hook useControl for env
- Add FormikEffect with 300ms debounceTime
- update validation of max nbrControl to max -(some of everyControls)
=> feat(control-env): maxNbrControl

frontend/src/features/common/components/ui/toogle-label.tsx, frontend/src/features/pam/mission/components/elements/actions/action-anti-pollution-form.tsx, frontend/src/features/pam/mission/components/elements/actions/action-control-env.tsx, frontend/src/features/pam/mission/components/elements/actions/action-illegal-immigration-form.tsx, frontend/src/features/pam/mission/components/elements/actions/action-rescue-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.test.tsx, frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.test.tsx, frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-navigation-form.tsx, frontend/src/features/pam/mission/components/elements/controls/env-control-form.test.tsx, frontend/src/features/pam/mission/components/elements/controls/env-control-form.tsx, frontend/src/features/pam/mission/hooks/action/use-action.test.tsx, frontend/src/features/pam/mission/hooks/action/use-action.tsx
- Control (layout
- Action 
- Env action (css, display errors)
=> Bug fix, clémence part 2

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMCulturalMaritime.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMEnvTraffic.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMIllegalFish.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMIllegalImmigration.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMMigrationRescue.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMNotPollutionControlSurveillance.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMOutOfMigrationRescue.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMPollutionControlSurveillance.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMSeaSafety.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMSovereignProtect.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMTableExport.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMVesselRescue.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/excel/ExportExcelFile.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMCulturalMaritimeTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMEnvTrafficTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMIllegalFishTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMIllegalImmigrationTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMMigrationRescueTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMNotPollutionControlSurveillanceTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMOutOfMigrationRescueTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMPolllutionControlSurveillanceTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMSeaSafetyTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMSovereignProtectTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMTableExportTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMVesselRescueTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/ExportMissionAEMTests.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/FillAEMExcelRowTest.kt
- Convert Int to Double
- fix filter on env actions illicites projects
=> fix(AEM): Int to Double / rejects illicites

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMIllegalFish.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMNotPollutionControlSurveillance.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMPollutionControlSurveillance.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMIllegalFishTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMNotPollutionControlSurveillanceTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMPolllutionControlSurveillanceTest.kt
- update algorithm for infractions with notice over env
- update nbr of infraction to count natinf instead of size
- update test
=> fix(AEM): infractions, natinf

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/infraction/InfractionEnvTargetEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/infraction/IsInfractionInvalidForVehicleType.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/InfractionController.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/adapters/infraction/InfractionWithNewTargetInput.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/infraction/InfractionEnvTarget.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/infraction/InfractionEnvTargetModel.kt, backend/src/main/resources/db/migration/V1.2024.09.25.11.26__infraction_env_target_drop_null_constraint.sql, backend/src/main/resources/graphql/infraction.graphqls, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/Infraction/IsInfractionInvalidForVehicleTypeTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/api/admin/bff/adapters/infractions/InfractionWithNewTargetInputTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/infraction/InfractionEnvTargetModelTest.kt
- alter db to allow null on vessel information for env
- graphQl allow null vessel infos and add vehicle type
- controller before anything check validity of vehicle type
- transfert data from controller to model
- Test it
=> feat(infraction): check infraction vehicle type allow null vessel info

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/InfractionController.kt, frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-navigation-form.tsx, frontend/src/features/pam/mission/components/elements/controls/control-security-form.tsx
J'ai du bouger des <Form> dans les controles parce que ca posait probleme avec le Form des infractions
=> fix(infractions): fix infractions not being submitted

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/infraction/InfractionsByVessel.kt, backend/src/main/resources/graphql/infraction.graphqls, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/bff/model/infraction/InfractionsByVesselTest.kt, frontend/src/features/common/types/infraction-types.ts, frontend/src/features/pam/mission/hooks/use-action-by-id.tsx
- In case vessel identifier is null, then group by person controlled
- update interfaces, graphql and typescript
- Test it
=> feat(infraction)- groupby controlled person also

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMIllegalFish.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMMigrationRescue.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMOutOfMigrationRescue.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMOutOfMigrationRescueTest.kt
- replace !! by ?:0
- Test that nbrOfPersonRescue=. null doesn't throw exception anymore
=> fix(AEM): null pointer exception over out of migrant nbrOfPersonRescue

backend/src/main/resources/db/migration/V1.2024.10.22.11.25__fix_crew_themis_b.sql
- second Themis id 37 has wring name
=> fix(agent): service themis b second missing

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/infraction/InfractionModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/repositories/mission/infraction/JPAInfractionEnvTargetRepository.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/repositories/mission/infraction/JPAInfractionRepository.kt
Petit amélioration perf/stabilité sur le lazy loading des natinfs dans les infractions
=> fix(Backend): fix lazy init error on InfractionModel.natinf

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/AEMIllegalFish.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/AEMIllegalFishTest.kt
- Add the number of natinf not the natInf itself
- Update test
=> feat(AEM): update  calcul to improve to the number of natinf

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/control/BaseControlEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/control/ControlAdministrativeEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/control/ControlGensDeMerEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/control/ControlNavigationEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/control/ControlSecurityEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/control/ControlAdministrativeModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/control/ControlGensDeMerModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/control/ControlModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/control/ControlNavigationModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/control/ControlSecurityModel.kt, backend/src/main/resources/db/migration/V1.2024.11.28.15.20__control_table_has_been_done_column.sql, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/control/ControlAdministrativeModelTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/control/ControlGensDeMerModelTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/control/ControlNavigationModelTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/model/mission/control/ControlSecurityModelTest.kt
- add hasBeenDone column to control's table
- Add hasBeenDone to model and transform method to Entity
- Add hasBeenDone to entity constructor
- Test control model
=> feat(control): add hasBeenDone attributes and column

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionAction.kt
=> fix(mission-action): parsing json

backend/src/main/resources/db/migration/V1.2025.01.06.15.20__ulam-service.sql, frontend/src/pages/signup.tsx
J'ai rajouté ça dans la page de signup, il faut mettre:
- serviceId = 9
- choisir ULAM
=> feat: update signup to add roles and add ULAM service for tests

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetEnvActionById.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetFishActionById.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetFishActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetNavActionById.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetNavActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/MissionActionRestController.kt
- Check validation of id before
=> fix(action): fix env fish action over uuid

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetEnvActionById.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetFishActionById.kt, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-add-action.tsx
- restriction over uuid into fish action
- Add logger to remove later
- Fix control modal not closing
=> fix(action): fish action + logger

frontend/src/v2/features/pam/components/element/mission-action-item-pam.tsx, frontend/src/v2/features/ulam/components/element/mission-action-item-ulam.tsx
- getting isMissionFinished for PAM and ULAM
=> fix(mission): dispatch isMissionFinished

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetEnvMissionById2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/cache/CaffeineConfiguration.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/cache/CaffeineConfigurationTest.kt
- resolve prod cache issue by adding another cache entry
=> fix(prod): cache issue

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionEnvAction.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionFishAction.kt, frontend/src/v2/features/common/components/layout/mission-page-header-wrapper.tsx, frontend/src/v2/features/common/services/use-create-mission-action.tsx, frontend/src/v2/features/common/services/use-delete-mission-action.tsx, frontend/src/v2/features/common/services/use-mission.tsx, frontend/src/v2/features/common/services/use-update-mission-action.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-header-action.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-header-completeness-for-stats.tsx, frontend/src/v2/features/mission-action/components/layout/mission-action-header-title-wrapper.tsx, frontend/src/v2/features/mission-action/components/layout/mission-action-header-wrapper.tsx, frontend/src/v2/features/mission-infraction/components/elements/mission-infraction-env-form.tsx, frontend/src/v2/features/mission-infraction/components/elements/mission-infraction-form.tsx, frontend/src/v2/features/mission-infraction/components/ui/mission-infraction-summary.tsx, frontend/src/v2/features/pam/components/element/mission-action-pam-header.tsx, frontend/src/v2/features/pam/components/element/mission-action-pam.tsx, frontend/src/v2/features/pam/components/element/mission-timeline-pam.tsx, frontend/src/v2/features/ulam/components/element/mission-action-ulam-header.tsx, frontend/src/v2/features/ulam/components/element/mission-action-ulam.tsx, frontend/src/v2/features/ulam/components/element/mission-timeline-ulam.tsx, frontend/src/v2/pages/mission-pam-page.tsx, frontend/src/v2/pages/mission-ulam-page.tsx
https://github.com/orgs/MTES-MCT/projects/30/views/1?pane=issue&itemId=94012909&issue=MTES-MCT%7Crapportnav2%7C502
=> fix(ulam):  review 2

frontend/src/v2/features/common/hooks/use-mission-general-informations-form.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-anti-pollution.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-env-control.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-fish-control.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-generic-date-observation.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-illegal-immigration.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-nav-control.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-rescue.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-surveillance.tsx, frontend/src/v2/features/mission-action/components/ui/mission-action-formik-date-range-picker.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-generic-date-observation.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-nav-control.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-rescue.tsx, frontend/src/v2/features/mission-action/types/action-type.ts, frontend/src/v2/features/ulam/components/element/mission-general-information-initial-form.tsx
- Update MissionActionFormikDateRangePicker to add a new form, init value & handleSubmit
- Use validation Schema simpleDateRangeValidationSchema
- Update all component using MissionActionFormikDateRangePicker
=> fix(MissionActionFormikDateRangePicker): component with his own form

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetComputeEnvActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetComputeFishActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetComputeNavActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetFishActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetMissionAction.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionAEM2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/MissionActionRestController.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/GetComputeEnvActionListByMissionIdTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/GetComputeFishActionListByMissionIdTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/GetComputeNavActionListByMissionIdTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/v2/GetFishActionListByMissionIdTest.kt, frontend/src/v2/features/mission-action/components/elements/mission-action-item-env-control.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-rescue.tsx, frontend/src/v2/features/mission-action/components/elements/mission-action-item-surveillance.tsx, frontend/src/v2/features/mission-action/components/ui/mission-action-formik-date-range-picker.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-rescue.tsx, frontend/src/v2/features/mission-action/validation-schema/date-validation.ts
- Create a separate useCase to getFishActions with cache
- Separate getEnvMission to cache and compute actions
- Rename UseCase to Add Compute
- Test the new useCase getFishActionListByMissionId
=> fix(backend): handle cache issue

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionAEMSingle2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionReports.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionReportsTest.kt
- AEM call mission-action
- fixed tests
=> fix(backend): AEM backend single on Mission-action

.gitlab-ci.yml, backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/CreateEnvMission.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/PatchEnvMission.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/CreateOrUpdateGeneralInfo.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/generalInfo/InterMinisterialService.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/generalInfo/MissionGeneralInfo2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/MissionGeneralInfoRestController.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/MissionRestController.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/generalInfo/MissionGeneralInfoModel.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/bff/controllers/MissionRestControllerTest.kt, frontend/package.json
- general info id == missionId
- add few missing attributes
=> fix(backend): general infos, create/ update fix

frontend/src/features/common/types/mission-types.ts, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-commerce.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-fishing.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-passenger.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-sailing-leisure.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-sailing-pro.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/icon-vessel-school.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/mission-control-selection.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-commerce.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-fishing.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-passenger.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-sailing-leisure.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-sailing-pro.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/icon-vessel-school.test.tsx, frontend/src/v2/features/common/components/ui/__tests__/mission-control-selection.test.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-commerce.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-fishing.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-passenger.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-sailing-leisure.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-sailing-pro.tsx, frontend/src/v2/features/common/components/ui/icon-vessel-school.tsx, frontend/src/v2/features/common/components/ui/mission-control-selection.tsx, frontend/src/v2/features/common/hooks/__tests__/use-vessel.test.tsx, frontend/src/v2/features/common/hooks/use-vessel.tsx, frontend/src/v2/features/mission-control/components/ui/mission-control-nav-summary.tsx, frontend/src/v2/features/mission-infraction/components/ui/mission-infraction-env-summary-by-cacem.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-add-action.tsx, frontend/src/v2/features/mission-timeline/components/layout/mission-timeline-Header-wrapper.tsx, frontend/src/v2/features/pam/components/element/mission-timeline-header-pam.tsx, frontend/src/v2/features/ulam/components/element/mission-timeline-header-ulam.tsx
- Add 2 new types of vessel
- show in create control
- Filter control over moduleType
- Replace geVesselType by getVesselTypeName
- tests it
=> fix(frontend): nbr control vessel ULAM

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/env/envActions/VesselTypeEnum.kt
=> fix(backend): vesselTypeEnum back

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/CreateOrUpdateGeneralInfo.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/ProcessMissionCrew.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/crew/v2/ProcessMissionCrewTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/mocks/mission/MissionCrewEntityMock.kt, frontend/src/v2/features/common/services/use-administrations.tsx, frontend/src/v2/features/common/services/use-agents.tsx, frontend/src/v2/features/common/services/use-control-unit-resources.tsx, frontend/src/v2/features/common/services/use-user.tsx
- List of crew member compare from db
- Delete missing, add new
- Test it
=> fix(backend): processing crew

.gitlab-ci.yml, backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionActionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionEnvActionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionFishActionEntity.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/mission/MissionEnvActionEntityTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/mission/MissionFishActionEntityTest.kt, frontend/package.json, frontend/src/v2/features/auth/components/auth-guard.tsx, frontend/src/v2/features/common/components/ui/formik-multi-select-natinf.tsx, frontend/src/v2/features/common/hooks/__tests__/use-mission-type.test.tsx, frontend/src/v2/features/common/hooks/__tests__/use-vessel.test.tsx, frontend/src/v2/features/common/hooks/use-mission-type.tsx, frontend/src/v2/features/common/services/use-control-unit-resources.tsx, frontend/src/v2/features/common/services/use-mission.tsx, frontend/src/v2/features/mission-general-infos/components/mission-general-information-control-unit-resource.tsx, frontend/src/v2/features/mission-infraction/components/elements/mission-infraction-env-form.tsx, frontend/src/v2/features/mission-infraction/components/elements/mission-infraction-env-item.tsx, frontend/src/v2/features/mission-infraction/components/elements/mission-infraction-env-list-form.tsx, frontend/src/v2/features/mission-infraction/components/ui/mission-infraction-vessel-form.tsx, frontend/src/v2/features/mission-infraction/hooks/use-infraction-env-form.tsx, frontend/src/v2/features/mission-timeline/components/ui/__tests__/__snapshots__/mission-timeline-item-control-card-subtitle.test.tsx.snap, frontend/src/v2/features/mission-timeline/components/ui/__tests__/mission-timeline-item-control-card-subtitle.test.tsx, frontend/src/v2/features/mission-timeline/components/ui/mission-timeline-item-control-card-Subtitle.tsx, frontend/src/v2/features/ulam/components/element/mission-general-information-form-ulam.tsx, frontend/src/v2/features/ulam/components/element/mission-general-information-initial-form-ulam.tsx
- https://github.com/orgs/MTES-MCT/projects/30/views/1?pane=issue&itemId=94012909&issue=MTES-MCT%7Crapportnav2%7C502
=> fix(frontend): v13 bugs fix

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/config/JwtEncodingConfig.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/crew/AgentServiceEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/crew/MissionCrewEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/UpdateMissionService.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/crew/GetActiveCrewForService.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/service/GetCrewByServiceId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/CrewRestController.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/crew/AgentServiceModel.kt, backend/src/main/resources/db/migration/V1.2025.03.04.14.52__update_agent_service.sql, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/UpdateMissionServiceTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/crew/GetActiveCrewForServiceTest.kt, frontend/src/v2/features/common/types/service-agents-types.ts, frontend/src/v2/pages/admin-crew-page.tsx
Deux choses ici : 
- update Gyptis A
- Rajouter de la colonne `disabled_at` dans la table `agent_service`
C'est super important de pas delete les rows dans `agent_service` sinon on perd l'historique des crews par mission
=> Crew updates

frontend/src/v2/features/auth/hooks/use-auth.tsx, frontend/src/v2/features/common/components/layout/__tests__/mission-list-page-header-wrapper.test.tsx, frontend/src/v2/features/common/components/ui/mission-page-header.tsx, frontend/src/v2/features/common/hooks/use-mission-list.tsx, frontend/src/v2/features/common/hooks/use-mission-tag.tsx, frontend/src/v2/features/common/types/query-key-type.ts, frontend/src/v2/features/mission-general-infos/components/mission-general-information-crew-no-comment.tsx, frontend/src/v2/pages/mission-list-ulam-page.tsx, frontend/src/v2/pages/mission-pam-page.tsx, frontend/src/v2/pages/mission-ulam-page.tsx
- move crew in mission-geenral-info feature
- unvalidate query when closing mission
=> fix(frontend): fix ulam crew update / reset query when closing mission

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/status/ActionStatusType.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionGeneralInfoEntity2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/GroupActionByDate2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolCombined2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolMultipleZipped2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolSingle2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionReports.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/FormatActionsForTimeline2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/GetInfoAboutAction2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/GetMissionOperationalSummary2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/MapStatusDurations2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/status/GetNbOfDaysAtSeaFromNavigationStatus2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/status/GetStatusDurations2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/GetMission2.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/v2/MissionRestController.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/v2/MissionGeneralInfoEntity2Tests.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolCombinedTest2.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolMultipleZippedTest2.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionReportsTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/GetMission2Test.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/bff/controllers/MissionRestControllerTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/mocks/mission/MissionEntityMock2.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/mocks/mission/MissionGeneralInfoEntity2Mock.kt, frontend/src/features/pam/mission/components/elements/controls/env-control-form.test.tsx, frontend/src/features/pam/mission/hooks/control/use-control.tsx
C'est beaucoup de nouveaux fichiers mais en gros, j'ai repris ceux qui existaient et j'ai adapté aux Entity v2, tout simplement
=> feat: adapt rapport de patrouille to v2

frontend/package-lock.json, frontend/package.json, frontend/src/v2/features/common/components/elements/offline-tag.tsx, frontend/src/v2/features/common/components/elements/online-toggle.tsx, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/formik-select-status-reason.test.tsx.snap, frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/formik-select-vessel-size.test.tsx.snap, frontend/src/v2/features/common/types/mission-action.ts, frontend/src/v2/features/common/types/network-types.ts, frontend/src/v2/features/mission-action/components/layout/__tests__/mission-action-header-wrapper.test.tsx, frontend/src/v2/features/mission-action/components/layout/mission-action-header-sync-status-banner.tsx, frontend/src/v2/features/mission-action/components/layout/mission-action-header-wrapper.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-env-control-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-fish-control-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-nav-control-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-note-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-rescue-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-status-card.tsx, frontend/src/v2/features/mission-timeline/components/elements/mission-timeline-item-surveillance-card.tsx, frontend/src/v2/features/mission-timeline/components/layout/__tests__/mission-timeline-item-card-wrapper.test.tsx, frontend/src/v2/features/mission-timeline/components/layout/__tests__/mission-timeline-item-sync-status.test.tsx, frontend/src/v2/features/mission-timeline/components/layout/mission-timeline-item-card-wrapper.tsx, frontend/src/v2/features/mission-timeline/components/layout/mission-timeline-item-sync-status.tsx, frontend/src/v2/features/mission-timeline/types/mission-timeline-output.ts, frontend/src/v2/features/pam/components/element/mission-timeline-pam-body.tsx
J'ai rajouté ces composants là, ils restent invisible par défaut tant que j'ai pas implémenté la vraie mécanique du offline first
=> feat(offline): add offline icon and banner in timeline + action details

frontend/src/v2/features/common/services/__tests__/use-missions.test.tsx, frontend/src/v2/features/common/services/use-mission.tsx, frontend/src/v2/features/common/services/use-missions.tsx
Depuis la homepage, ajout du prefetch de chaque mission en vue du offline
=> feat: prefetch missionById after loading missions

frontend/src/v2/features/common/hooks/__tests__/use-offline-since.test.tsx, frontend/src/v2/features/common/hooks/use-offline-since.tsx, frontend/src/v2/features/common/hooks/use-online-manager.tsx, frontend/src/v2/features/pam/components/ui/__tests__/offline-dialog.test.tsx, frontend/src/v2/features/pam/components/ui/offline-dialog.tsx, frontend/src/v2/pages/mission-pam-page.tsx, frontend/src/v2/store/index.ts, frontend/src/v2/store/slices/connectivity-reducer.ts
=> feat(offline): add dialog inviting users to reconnect after 24h

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionActionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/CreateOrUpdateGeneralInfo.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/ProcessMissionCrew.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/UpdateMissionService2.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/crew/v2/ProcessMissionCrewTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/CreateOrUpdateGeneralInfoTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/UpdateMissionService2Test.kt
Petits problemes concernant le crew coté pam, les endpoint ne renvoyaient pas toujours le crew
=> fix: fix PAM crew updates

frontend/src/v2/features/common/components/layout/__tests__/__snapshots__/mission-list-page-content-wrapper.test.tsx.snap, frontend/src/v2/features/common/components/layout/mission-list-page-content-wrapper.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-illegal-immigration.tsx, frontend/src/v2/features/mission-action/hooks/use-mission-action-rescue.tsx, frontend/src/v2/features/pam/components/element/mission-action-pam-item.tsx, frontend/src/v2/features/pam/hooks/use-pam-mission-general-information-form.tsx, frontend/src/v2/features/ulam/components/element/mission-action-item-ulam.tsx
- fix qui faisait que useUpdateAction était appelé automatiquement quand on allait sur le deetail de l'action
- Les NumberInput n'acceptent pas de valeurs négatives
=> Various v2 fixes

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/BaseMissionNavAction.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/v2/MissionNavActionEntity.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/repositories/mission/action/INavMissionActionRepository.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetComputeNavActionListByMissionId.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/PatchMissionEnv.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionAction.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionNavAction.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/api/bff/model/v2/MissionNavActionData.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/action/v2/MissionActionModel.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/repositories/interfaces/mission/action/IDBMissionActionRepository.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/repositories/mission/action/JPAMissionActionRepository.kt, backend/src/main/resources/db/migration/V1.2025.07.01.16.03__update_mission_action_table.sql, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/mission/MissionNavActionEntityTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/GetComputeNavActionListByMissionIdTest.kt, backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/mocks/mission/action/MissionActionModelMock.kt, frontend/src/v2/features/common/types/mission-action.ts
- uppdate database column
- update Model/ jpa / entity /
- update test
- front interface
=> feat(backend): missionAction rename mission_id_uuid to owner_id

backend/src/main/resources/graphql/action-fish.graphqls, backend/src/main/resources/graphql/action.graphqls
- Accepting startdate null in every nav action
- But not accepting startdate input null in action
=> fix(backend): nullable start date

frontend/src/features/common/components/ui/icon/IconVesselCommerce.tsx, frontend/src/features/common/components/ui/icon/IconVesselFishing.tsx, frontend/src/features/common/components/ui/icon/IconVesselSailingLeisure.tsx, frontend/src/features/common/components/ui/icon/IconVesselSailingPro.tsx, frontend/src/features/common/components/ui/icon/IconVesselServices.tsx
=> fix: fix svg import for boat images

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/config/SecurityConfig.kt, backend/src/main/resources/application.properties
- Add swagger to build gradle
- Config it for env but not prod
- redefined the ui path
=> feat(backend): swagger dependency installation

frontend/src/v2/features/mission-target/hooks/use-target.tsx
la méthode toSpliced est assez récente et le firefox de ma VM tourne sur une verison trop vieille donc ca marche pas
=> fix: fix delete infraction browser compatibility

frontend/src/v2/features/common/components/ui/__tests__/time-conversion.test.tsx, frontend/src/v2/features/common/components/ui/time-conversion.tsx, frontend/src/v2/features/inquiry/components/ui/inquiry-header.tsx, frontend/src/v2/features/pam/components/element/mission-header-pam.tsx, frontend/src/v2/features/ulam/components/element/__tests__/mission-create-dialog.test.tsx, frontend/src/v2/features/ulam/components/element/mission-create-dialog.tsx, frontend/src/v2/features/ulam/components/element/mission-header-ulam.tsx
- Add border around dialog
- Add time conversion helper for user
- update tests
=> feat(frontend): dialog creation mission

frontend/src/features/pam/missions/hooks/use-missions.tsx, frontend/src/pages/mission-page.tsx, frontend/src/query-client/axios.ts
- add Poll interval 300000
- Update axios timeout 900000
- remove cache clear and evict
=> fix(frontend):  update params network and fetching

backend/build.gradle.kts
Reverts MTES-MCT/rapportnav2#840
=> Revert "chore(deps): bump org.apache.tomcat.embed:tomcat-embed-core from 10.1.42 to 10.1.44 in /backend in the gradle group across 1 directory"

backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/fish/fishActions/SpeciesControl.kt, backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/FakeActionData.kt, backend/src/main/resources/wiremock/fish/actions.json
Un fix sur le nom des espèces pêchées, ca marchait en local mais pas avec la vraie API de Fish
=> fix: deserialize speciesName from Fish correctly
