MTES-MCT/rapportnav2

- .github/workflows/codeql.yml
- .github/workflows/release.yml
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/mission/nav/action/ActionStatusEntity.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/GetStatusForAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/bff/adapters/action/ActionStatusInput.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/bff/model/action/Action.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/bff/model/action/ActionData.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/database/model/mission/action/ActionStatusModel.kt
- backend/src/main/resources/db/migration/V1.2024.01.30.11.54__status_drop_isstart.sql
- backend/src/main/resources/graphql/action.graphqls
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/status/GetStatusForActionTests.kt
- frontend/src/pam/mission/actions/action-status-form.tsx
- frontend/src/pam/mission/actions/use-action-by-id.tsx
- frontend/src/pam/mission/mission-content.tsx
- frontend/src/pam/mission/queries.ts
- frontend/src/pam/mission/status/use-add-update-status.tsx
- frontend/src/pam/mission/timeline/item/timeline-item-status.test.tsx
- frontend/src/pam/mission/timeline/item/timeline-item-status.tsx
- frontend/src/pam/mission/timeline/item/timeline-item.test.tsx
- frontend/src/pam/mission/timeline/use-mission-timeline.tsx
- frontend/src/types/action-types.ts
C'est par rapport au fait que les commandants voulaient auto-fermer un status quand ils en créent un nouveau.
A la base, on affichait un status de début et un status de fin mais c'était vraiment galère de gérer cette fermeture avec début et fin.
Du coup, on a simplifié et on a que des statuts de début en fait.
Donc quand on remplira le rapport de patrouille, il faudra loop sur tous les statuts et compter les diff entre 2 statuts pour avoir la durée.
> Back & Front - remove isStart for status action

- .github/workflows/trivy-db.yml
- .github/workflows/trivy.yml
- .gitlab-ci.yml
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/infrastructure/database/AbstractDBTests.kt
- infra/docker-compose.local.yml
- jobs-build-CI/deploiement/docker-compose.yml.j2
Plusieurs choses ici: 
- updaté les criteres de sévérité histoire de matcher 100% avec la DSI
- séparé l'action Trivy en 2 actions, une qui check l'OS et une autre les libs parce que la DSI fait pareil et n'applique pas les mêmes sévérités selon le cas
- bumpé postres à 15.7
Autre piste d'optimisation:
Pour analyser des images docker, il faut build le container.
Je sais pas pourquoi j'ai fait une usine à gaz qui push un build docker dans notre propre github package manager (https://github.com/MTES-MCT/rapportnav2/pkgs/container/rapportnav2%2Frapportnav-app)
Je pense que c'est absolument pas nécessaire. Build en local et analyser ce build local me parait moins gros que tu push un build sur un package manager
> fix(Trivy): update severity params

- .github/workflows/trivy-db.yml
- .github/workflows/trivy.yml
- backend/build.gradle.kts
Au lieu de faire une usine à gaz et construire une image docker à chaque commit, il s'agit maintenant de scanner le repo: https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#using-trivy-to-scan-your-git-repo
> refactor(ci): scan file system instead of building a container

- frontend/package-lock.json
- frontend/package.json
- frontend/src/apollo-client.ts
- frontend/src/pam/mission/crew/mission-crew-form.test.tsx
- frontend/src/pam/mission/crew/mission-crew-form.tsx
- frontend/src/pam/mission/crew/mission-crew-member-list.test.tsx
- frontend/src/pam/mission/crew/mission-crew-member-list.tsx
- frontend/src/pam/mission/crew/mission-crew.test.tsx
- frontend/src/pam/mission/crew/mission-crew.tsx
- frontend/src/pam/mission/crew/use-add-update-mission-crew.tsx
- frontend/src/test-utils.tsx
- frontend/src/ui/text.test.tsx
- frontend/src/ui/text.tsx
- Create a new list of crew member layout with comment
- Display a Dialog for adding a new member or updating an existing one
- Add a form with validation
- trigger delete / addOrUpdateCrew mutation
- tests
> feat(mission-crew): Refacto mission-crew with comment

- frontend/src/pam/mission/crew/mission-crew-member-list.tsx
- frontend/src/pam/mission/crew/mission-crew.tsx
- frontend/src/pam/mission/crew/use-add-update-mission-crew.tsx
- Modify layout to add width 100% on stack item
- Update mutation parameter, missionId: Number instead of string
> fix(frontend): mission list team member layout and mutation

- frontend/src/pam/mission/crew/mission-crew-member-list.test.tsx
- frontend/src/pam/mission/timeline/use-mission-timeline.tsx
La colonne centrale de l'app ne se met à jour que si une action est faite mais en réalité, c'est pas optimal parce qu'il y a un long temps d'inactivité entre 2 sessions rapportnav pour un commandant. 
Du coup, quand il/elle réouvre rapportnav, les dernieres actions ajoutées par CNSP/CACEM ne sont pas visible, ce qui est un peu confusant.
Lors des retex, c'était assez flag que ca les perturbait.
> feat(polling): add polling 5min on mission timeline query

- frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-administrative-form.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-gens-de-mer-form.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-navigation-form.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-navigation-form.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-security-form.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-security-form.tsx
- frontend/src/features/pam/mission/components/ui/control-title-checkbox.tsx
- frontend/src/features/pam/mission/hooks/control/use-control.test.tsx
- frontend/src/features/pam/mission/hooks/control/use-control.tsx
- frontend/src/test-utils.tsx
- use FormikEffect and Formik component
- Add timer to delay mutation
- Test eveything
> feat(control-administrative): delay form mutation for 5 sec

- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-control-env.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-control-fish.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-surveillance.tsx
La couleur du texte change pour respecter le "branding" de MonitorEnv et Fish  (sans la bordure, juste le texte)
> fix(frontend): update fish/env text color in timeline

- frontend/src/features/pam/mission/components/elements/actions/fish/fish-control-administrative-section.tsx
- frontend/src/features/pam/mission/components/elements/actions/fish/fish-control-engines-section.tsx
On utilisait la mauvaise prop pour passer un form element en readonly
> fix(frontend): use correct readonly prop on Fish action form

- frontend/src/features/pam/mission/components/elements/controls/env-control-form.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/env-control-form.tsx
- frontend/src/features/pam/mission/hooks/control/use-control.test.tsx
- frontend/src/features/pam/mission/hooks/control/use-control.tsx
- update validation mode... don't trigger if form is not valid
- update trigger point.. don't trigger if checkbox is checked but no value
- test it
> feat(control-env): checkbox /  formikEffect

- frontend/src/features/common/types/infraction-types.ts
- frontend/src/features/pam/mission/components/elements/actions/action-control-env.tsx
- frontend/src/features/pam/mission/components/elements/infractions/env-infraction-add-new-target.tsx
- frontend/src/features/pam/mission/components/elements/infractions/env-infraction-target-added-by-unit-form.test.tsx
- frontend/src/features/pam/mission/components/elements/infractions/env-infraction-target-added-by-unit-form.tsx
[UPDATE]
Cas : 
1. **Personne physique**
On affiche "Identité de la personne controlée" `identityControlledPerson`
2. **Personne morale**
On affiche "Identité de la personne morale controlée" `identityControlledPerson`
3. **Véhicule**
On affiche le champ immatriculation du véhicule `vesselIdentifier`
4. **Véhicule de type vessel**
On garde ce qu'on avait déjà, à savoir  `vesselSize` `vesselType`  `vesselIdentifier` `identityControlledPerson`
> feature(347) Improvement of infraction form field management based on target type

- frontend/src/features/common/components/elements/date-picker.test.tsx
- frontend/src/features/common/components/elements/daterange-picker.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-baaem-permanence-form.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-control-env.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-env-daterange.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-fish-daterange.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-representation-form.test.tsx
- frontend/src/features/pam/mission/components/elements/actions/action-surveillance-env.test.tsx
- frontend/src/features/pam/mission/components/elements/controls/control-security-form.tsx
- frontend/src/features/pam/mission/components/elements/infractions/env-infraction-target-added-by-unit-form.test.tsx
- frontend/src/features/pam/mission/components/elements/mission-daterange.test.tsx
- frontend/src/features/pam/mission/components/elements/mission-item.tsx
- frontend/src/features/pam/mission/components/elements/mission-service.test.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-anti-pollution.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-baaem-permanence.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-container.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-illegal-immigration.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-nautical-event.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-public-order.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-representation.tsx
- frontend/src/features/pam/mission/components/elements/timeline/item/timeline-item-vigimer.tsx
- frontend/src/features/pam/mission/components/elements/timeline/timeline.test.tsx
- frontend/src/features/pam/mission/components/layout/page-footer.tsx
- frontend/src/features/pam/mission/hooks/representation/use-add-representation.tsx
- frontend/src/pages/mission-page.test.tsx
- frontend/src/pages/mission-page.tsx
- remove front unused var or import
> fix(warning): remove front dead code

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMCulturalMaritime2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMEnvTraffic2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMIllegalFish2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMIllegalImmigration2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMMigrationRescue2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMNotPollutionControlSurveillance2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMOutOfMigrationRescue2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMPollutionControlSurveillance2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMSeaSafety2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMSovereignProtect2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMTableExport2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/entities/aem/v2/AEMVesselRescue2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetEnvMissionById.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionAEM2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/utils/FillAEMExcelRow.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/utils/AEMUtils.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMCulturalMaritimeTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMEnvTrafficTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMIllegalFishTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMIllegalImmigrationTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMMigrationRescueTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMNotPollutionControlSurveillanceTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMOutOfMigrationRescue2Test.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMPolllutionControlSurveillanceTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMSeaSafetyTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMSovereignProtectTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMTableExportTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/entities/aem/v2/AEMVesselRescueTest2.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/GetEnvMissionByIdTest.kt
- Create V2 of every cell of tableau export
- Create a V2 for TableauExport class
- Create a V2 test for every class
> feat(AEM): v2 of AEM base on mission-action

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/GetNavActionById.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/utils/UUIDUtils.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/GetNavActionByIdTest.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/utils/UUIDUtilsTest.kt
https://sentry.incubateur.net/organizations/betagouv/issues/142488/?query=is%3Aunresolved&referrer=issue-stream&stream_index=2
> fix: check actionId is a valid UUID in GetNavActionById.kt

- frontend/src/v2/features/common/components/layout/mission-page-header-wrapper.tsx
- frontend/src/v2/features/common/hooks/use-mission-report-export.tsx
- frontend/src/v2/features/common/hooks/use-mission-timeline.tsx
- frontend/src/v2/features/common/hooks/use-mission-type.tsx
- frontend/src/v2/features/common/hooks/use-mission.tsx
- frontend/src/v2/features/common/services/use-mission.tsx
- frontend/src/v2/features/common/types/mission-types.ts
- frontend/src/v2/features/mission-action/components/elements/mission-action-header-action.tsx
- frontend/src/v2/features/mission-action/components/elements/mission-action-item-control.tsx
- frontend/src/v2/features/mission-control/components/elements/mission-control-env-form.tsx
- frontend/src/v2/features/mission-timeline/components/layout/mission-timeline-wrapper.tsx
- frontend/src/v2/features/mission-timeline/hooks/use-timeline-complete-for-stats.tsx
- frontend/src/v2/features/mission-timeline/hooks/use-timeline.tsx
- frontend/src/v2/features/pam/components/element/mission-action-pam.tsx
- frontend/src/v2/features/pam/components/element/mission-list/mission-list-header-pam.tsx
- frontend/src/v2/features/ulam/components/element/mission-action-item-ulam.tsx
- frontend/src/v2/features/ulam/components/element/mission-action-ulam.tsx
- frontend/src/v2/features/ulam/components/element/mission-general-information-initial-form.tsx
- frontend/src/v2/features/ulam/components/element/mission-list/mission-list-header-ulam.tsx
- frontend/src/v2/pages/mission-pam-page.tsx
- frontend/src/v2/pages/mission-ulam-page.tsx
- frontend/src/v2/store/index.ts
- frontend/src/v2/store/slices/general-infos-complete-for-stats-reducer.ts
- frontend/src/v2/store/slices/mission-reducer.ts
- frontend/src/v2/store/slices/timeline-complete-for-stats-reducer.ts
- Service to get mission
- hook to calculate status
- hook to compute completeness for actions
- add store's entries on timeline / general infos(completeness for stats)
- add store's entries on mission (status/ isMissionFinished
> feat(mission): compute status and complete for stats (front)

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/export/v2/ExportMissionPatrolSingle.kt
Revisite du calcul de durée de mission comme validé dans la sync dev
On utilise maintenant la somme des durées des status plutot que les dates de début/fin de mission
> fix(RapportPatrouille): use sum of statuses to compute mission duration

- frontend/src/v2/pages/mission-list-ulam-page.tsx
En ce moment, 2 fetch vers l'endoit /missions partent à cause des dates qui changent avec useEffect donc j'ai réparé ça
> fix: fix double fetch on homepage ulam

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/PatchEnvMission.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/PatchEnvAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/PatchFishAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/infrastructure/cache/CaffeineConfiguration.kt
- frontend/src/features/pam/mission/hooks/use-mission-by-id.tsx
- frontend/src/features/pam/mission/hooks/use-mission-timeline.tsx
Je pense que j'ai trouvé pour le bug des observationsByUnit qui sautent, c'était pas une histoire de cache parce qu'il était déjà evict lors du PatchEnvMission. J'en ai profité pour evict le cache v2 aussi.
C'était plutot un probleme que le field était pas redemandé dans certaines query graphql qui partageaient la meme key
> fix: fix flickering observationsByUnit

- frontend/src/v2/features/common/components/elements/__tests__/online-toggle.test.tsx
- frontend/src/v2/features/common/components/elements/online-toggle.tsx
- frontend/src/v2/features/common/components/ui/__tests__/__snapshots__/mission-page-footer.test.tsx.snap
- frontend/src/v2/features/common/hooks/__tests__/use-online-manager.test.tsx
- frontend/src/v2/features/common/hooks/use-online-manager.tsx
PR séparée pour te montrer les changements autour du hook et du toggle pour le offline
- Le hook
- fix pour pas repasser online alors qu'il n'y a vraiment plus de network
- introduction de `hasNetwork` qui check vraiment la connectivité réelle
- Toggle
-  ajout du disabled state quand il n'y a pas de network
> feat(Online): improve online hook and toggle component

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/GetStatusForAction2.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/AbstractGetMissionAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/ProcessEnvAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/ProcessFishAction.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/action/v2/ProcessNavAction.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/v2/ProcessEnvActionTest.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/v2/ProcessFishActionTest.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/action/v2/ProcessNavActionTest.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/status/GetStatusForAction2Tests.kt
Je comprenais pas pourquoi le statut des actions était complètement incohérent en local mais en fait, c'est parce qu'on utilisais les ActionStatus v1, cad la table 'mission_action_status' au lieu de 'mission_action'
> fix: compute correct action status in v2 archi

- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/GetMissions.kt
- backend/src/main/kotlin/fr/gouv/dgampa/rapportnav/domain/use_cases/mission/v2/GetNavMissions.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/GetMissionsTest.kt
- backend/src/test/kotlin/fr/gouv/gmampa/rapportnav/domain/use_cases/mission/v2/GetNavMissionsTest.kt
J'ai rajouté un filtre par serviceId sur GetNavMissions (de la table mission) parce que sinon, ca retournait aussi les missionsNav qu'on créait pour ULAM
> fix: GetNavMissions filter by serviceId
